[battery.critical]
label = ''
charging_label = ''
color = '#bf616a'
threshold = 5.0

[battery.low]
label = ''
charging_label = ''
color = '#bf616a'
threshold = 25.0

[battery.normal]
label = ''
charging_label = ''
color = '#e5e9f0'
threshold = 75.0

[battery.high]
label = ''
charging_label = ''
color = '#a3be8c'
threshold = 98.0

[battery.full]
label = ''
charging_label = ''
color = '#a3be8c'
threshold = 100.0