#!/bin/sh
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

#set background
feh --bg-scale "$SCRIPTPATH"/down.jpg

eww -c $EWW_CONFIG close-all 
eww -c $EWW_CONFIG kill

pkill eww

leftwm command "UnloadTheme"

pkill picom
# pkill polybar
pkill dunst
