#!/bin/sh
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

export STARSHIP_CONFIG="$SCRIPTPATH/.config/starship.toml"
export EWW_CONFIG="$SCRIPTPATH/.config/eww/dark-nord"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Boot picom or compton if it exists
picom --experimental-backends --config "$SCRIPTPATH"/picom.conf > /dev/null &

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"

# # Set background
feh --bg-scale "$SCRIPTPATH"/wallpapers/background1.jpg 

dunst &

eww -c $EWW_CONFIG daemon
sleep 1
index=0
# leftwm-state -q -n -t "$SCRIPTPATH"/sizes.liquid | sed -r '/^\s*$/d' | while read -r width
# do
#   barname="mainbar$index"
#   monitor="$(polybar -m | awk -v i="$(( index + 1 ))" 'NR==i{print}' | sed s/:.*// | tr -d '\n')"
#   monitor=$monitor width=$(( width - 16 )) polybar -c "$SCRIPTPATH"/polybar.config $barname &
#   index=$((index+1))
# done
eww -c $EWW_CONFIG open bar
eww -c $EWW_CONFIG open bar_second
eww -c $EWW_CONFIG open bar_third