format = """
[╭─ $username$hostname$directory$fill](dimmed white)
[│](dimmed white) $kubernetes$git_branch$git_commit$git_status$git_state$rust$package
[╰─](dimmed white)$character"""

[username]
style_user = "cyan"

[hostname]
style = "cyan"

[git_branch]
style = "bold cyan"
symbol = " "

[fill]
symbol = "─"
style = "dimmed white"

[git_state]
style = "bold yellow"
merge = "[ MERGING]($style)"
rebase = "[ REBASE]($style)"
cherry_pick = "[ PICKING]($style)"

[git_status]
style = "bold white"
conflicted = "[ ](red)"
up_to_date = "[ ](green)"

[git_commit]
style = "italic cyan"

[rust]
style = "bold cyan"

[package]
style = "bold green"

[directory]
style = "bold blue"

[gcloud]
disabled = true

[aws]
disabled = true

[kubernetes]
format = 'on [ﴱ ](blue)[$context ](italic bright-white)'
disabled = false

[kubernetes.context_aliases]
# rename every OpenShift cluster at once:
".*/(?P<cluster>[\\w-]+)/.*" = "$cluster"
"(?P<cluster>.*)/[\\w-]+:6443/.*" = "$cluster"

# Contexts from GKE, AWS and other cloud providers usually carry additional information, like the region/zone.
# The following entry matches on the GKE format (`gke_projectname_zone_cluster-name`)
# and renames every matching kube context into a more readable format (`gke-cluster-name`):
"gke_.*_(?P<cluster>[\\w-]+)" = "gke-$cluster"